build-push--job:
  image: docker:stable

  services:
    - docker:dind
    - name: docker:dind
      alias: thedockerhost
  variables:
    DOCKER_HOST: tcp://thedockerhost:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t soynico/dh-infra-ii:$CI_COMMIT_SHORT_SHA .
    - docker tag soynico/dh-infra-ii:$CI_COMMIT_SHORT_SHA soynico/dh-infra-ii:latest
    - docker push soynico/dh-infra-ii
  only:
    - main

