stages:   # Los distintos “pasos” que ejecutará nuestro pipeline
  - build
  - test

build-job:      # donde compilaremos el código
  stage: build  
  script:
    - echo "Compiling the code..."
    - javac Fibonacci.java
    - echo "Compile complete."
  tags:
    - java
  artifacts:
    paths:
      - Fibonacci.class
      
build-job-parallel:
  stage: build
  script:
    - echo "Solamente estoy esperando 5 segundos"
    - sleep 5
  tags:
    - java

test-job:
  stage: test
  script:
    - echo "Testing"
    - java Fibonacci
  tags:
    - java
